version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    target-branch: main
    open-pull-requests-limit: 1
    labels:
      - dependabot
      - security
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]

  - package-ecosystem: docker
    directory: /.devcontainer
    schedule:
      interval: monthly
    target-branch: main
    open-pull-requests-limit: 1
    labels:
      - dependabot
      - security
