version: '3.8'
services:
  database:
    image: mysql:8.0.30
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: sayyara
    ports:
      - 3306:3306
    volumes:
      - db-data:/var/lib/mysql
    healthcheck:
      test: mysql --database=$$MYSQL_DATABASE --password=$$MYSQL_ROOT_PASSWORD --user=root --execute='select 1'
      interval: 10s
      timeout: 30s
      retries: 10
      start_period: 5s

volumes:
  db-data:
