name: Lint Application
on:
  pull_request:
    branches:
      - main
    paths:
      - src/**
      - test/**
      - prisma/**

jobs:
  lint_app:
    name: 🧽 Lint and Typecheck Application
    runs-on: ubuntu-latest
    steps:
      - name: 🛎 Checkout
        uses: actions/checkout@v3

      - name: 💻 Setup Node
        uses: actions/setup-node@v3.6.0
        with:
          node-version: "16"

      - name: 💿 Cache Node Modules
        uses: actions/cache@v3
        env:
          cache-name: cache-node-modules
        with:
          # npm cache files are stored in `~/.npm` on Linux/macOS
          path: ~/.npm
          key: "${{ runner.os }}-build-${{ env.cache-name }}\
            -${{ hashFiles('**/package-lock.json') }}"
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - name: 🚧 Install Dependencies
        run: npm ci

      - name: 🧽 Run Typecheck
        run: npx tsc --project ./tsconfig.json

      # Fails on validation errors (line 1) and formatting errors (line 2)
      - name: 🧽 Run Prisma Validation
        run: |
          npx prisma format
          if [[ -n $(git status --porcelain=v1) ]]; then echo 'Prisma Schema Formatting Error' && exit 1; fi

      - name: 🧽 Run Prettier
        run: npx prettier --check '**/*.{ts,tsx,json,js,mjs,css,yml,yaml}'

      - name: 🧽 Run ESLint
        run: npx next lint
